version: "3.7"
services:
    db:
        image: mariadb
        restart: always
        volumes:
            - ./docker/mariadb/data:/var/lib/mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: 123456

    php-fpm:
        build: ./docker/php-fpm
        image: xxt/php-fpm
        volumes:
            - .:/usr/share/nginx/html

    nginx:
        build: ./docker/nginx
        image: xxt/nginx
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - .:/usr/share/nginx/html
        links:
            - php-fpm
        ports:
            - 8000:80

    adminer:
        image: adminer
        restart: always
        ports:
            - 9090:8080
